/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javasshdemo;

import java.io.IOException;
import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.SftpException;

public class App {

    private static final String HOST = "dcc-login.oit.duke.edu";
    private static final String USERNAME = "xh123";
    private static final String PRIVATEKEY_PATH = "~/.ssh/id_rsa";
    private static final String KNOWNHOSTS_PATH = "~/.ssh/known_hosts";

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws JSchException, IOException, SftpException, InterruptedException {
        System.out.println(new App().getGreeting());

        testSSH();
        // testS3();
    }

    public static void testSSH() throws JSchException, IOException, SftpException, InterruptedException {
        SSHService sshService = new SSHService(HOST, USERNAME, PRIVATEKEY_PATH,
                KNOWNHOSTS_PATH);

        sshService.execCommands("whoami");
        // sshService.execCommands("mkdir test-jsch");
        // sshService.sftpFromLocal("../hello-world.sh", "./test-jsch/hello-world.sh");
        // sshService.execCommands("cd test-jsch", "chmod 0700 hello-world.sh",
        // "./hello-world.sh");
        // sshService.sftpFromRemote("./test-jsch/helloworld.txt", "../helloworld.txt");

        sshService.close();
    }

    public static void testS3() throws IOException {
        AwsS3Service s3 = new AwsS3Service();
        s3.uploadObj("aipb.duke.bucket1", "test-key-1", "Hello World???".getBytes());
        byte[] bytes = s3.getObj("aipb.duke.bucket1", "test-key-1");
        System.out.println(new String(bytes));
        s3.deleteObj("aipb.duke.bucket1", "test-key-1");
    }

}
