/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javasshdemo;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

import com.jcraft.jsch.ChannelExec;
import com.jcraft.jsch.JSch;
import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.Session;

public class App {

    private static final String HOST = "vcm-34287.vm.duke.edu";
    private static final String USERNAME = "xh123";
    private static final String PASSWORD = "";

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws JSchException, IOException {
        System.out.println(new App().getGreeting());
        try {
            JSch jsch = new JSch();
            Session session = jsch.getSession(USERNAME, HOST);
            session.setPassword(PASSWORD);
            session.setConfig("StrictHostKeyChecking", "no");
            session.connect(5000);

            ChannelExec channel = (ChannelExec) session.openChannel("exec");
            channel.setCommand("whoami");
            channel.setInputStream(null);
            InputStream in = channel.getInputStream();
            channel.connect(5000);

            BufferedReader reader = new BufferedReader(new InputStreamReader(in));
            String line;
            while ((line = reader.readLine()) != null) {
                System.out.println(line);
            }

            channel.disconnect();
            session.disconnect();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
